/**
 * NJUPT Xianlin Campus — POI Data
 * 南京邮电大学仙林校区 — 兴趣点数据
 */

const CAMPUS_CENTER = [32.1115, 118.9065];

// Leaflet-style [[south, west], [north, east]]
const CAMPUS_BOUNDS = [[32.1040, 118.8965], [32.1200, 118.9155]];

// Bounds used to pin the campus-map image overlay
const CAMPUS_IMAGE_BOUNDS = [[32.1050, 118.8985], [32.1195, 118.9145]];

// ─── Categories ────────────────────────────────────────────────────────────
const CATEGORIES = {
  gate:     { label_en: 'Gates',          label_zh: '校门',  color: '#e74c3c', icon: '🚪' },
  admin:    { label_en: 'Administration', label_zh: '行政',  color: '#8e44ad', icon: '🏛️' },
  academic: { label_en: 'Academic',       label_zh: '教学',  color: '#2980b9', icon: '🎓' },
  food:     { label_en: 'Dining',         label_zh: '餐饮',  color: '#e67e22', icon: '🍜' },
  courier:  { label_en: 'Courier',        label_zh: '快递',  color: '#16a085', icon: '📦' },
  service:  { label_en: 'Services',       label_zh: '服务',  color: '#d4ac0d', icon: '🔧' },
  sports:   { label_en: 'Sports',         label_zh: '体育',  color: '#27ae60', icon: '⚽' },
  dorm:     { label_en: 'Dormitories',    label_zh: '宿舍',  color: '#7f8c8d', icon: '🏠' },
  landmark: { label_en: 'Landmarks',      label_zh: '地标',  color: '#2c3e50', icon: '🗿' },
};

// ─── Preset view filters ────────────────────────────────────────────────────
const NEW_STUDENT_IDS = [
  'gate-south', 'gate-north', 'gate-east', 'gate-west',
  'admin-south', 'admin-north', 'isu-office',
  'library', 'canteen-south', 'canteen-north',
  'clinic', 'courier-cainiao', 'courier-ems', 'atm-east',
  'supermarket', 'flag-square',
];

const DAILY_LIFE_IDS = [
  'canteen-south', 'canteen-north',
  'courier-jd', 'courier-sf', 'courier-cainiao', 'courier-ems',
  'atm-east', 'atm-center',
  'clinic', 'supermarket', 'bookstore',
  'repair-shop', 'mobile-topup',
];

// ─── Points of Interest ─────────────────────────────────────────────────────
const POIS = [
  // ── GATES ──────────────────────────────────────────────────────────────
  {
    id: 'gate-south', category: 'gate',
    name_zh: '南门（正门）', name_en: 'South Gate (Main Entrance)',
    coords: [32.1058, 118.9065],
    desc_en: 'Main entrance to NJUPT Xianlin Campus. Multiple bus routes stop nearby.',
    desc_zh: '南京邮电大学仙林校区正门，多条公交线路在此停靠。',
    tags_en: ['Main Gate', 'Transportation', 'Entry Point'],
    tags_zh: ['正门', '交通', '入口'],
  },
  {
    id: 'gate-north', category: 'gate',
    name_zh: '北门', name_en: 'North Gate',
    coords: [32.1188, 118.9020],
    desc_en: 'North entrance to campus.',
    desc_zh: '校区北部入口。',
    tags_en: ['Gate', 'Entry'], tags_zh: ['大门', '入口'],
  },
  {
    id: 'gate-east', category: 'gate',
    name_zh: '东门', name_en: 'East Gate',
    coords: [32.1120, 118.9135],
    desc_en: 'East entrance to campus.',
    desc_zh: '校区东部入口。',
    tags_en: ['Gate', 'Entry'], tags_zh: ['大门', '入口'],
  },
  {
    id: 'gate-west', category: 'gate',
    name_zh: '西门', name_en: 'West Gate',
    coords: [32.1115, 118.8988],
    desc_en: 'West entrance to campus.',
    desc_zh: '校区西部入口。',
    tags_en: ['Gate', 'Entry'], tags_zh: ['大门', '入口'],
  },

  // ── ADMINISTRATION ──────────────────────────────────────────────────────
  {
    id: 'admin-south', category: 'admin',
    name_zh: '行政南楼', name_en: 'Administrative Building (South)',
    coords: [32.1065, 118.9060],
    desc_en: 'Main administrative offices. New students register here for enrolment procedures.',
    desc_zh: '主要行政办公楼。新生在此办理入学注册手续。',
    tags_en: ['Registration', 'Administration', 'New Students'],
    tags_zh: ['注册', '行政', '新生'],
  },
  {
    id: 'admin-north', category: 'admin',
    name_zh: '行政北楼', name_en: 'Administrative Building (North)',
    coords: [32.1078, 118.9032],
    desc_en: 'Administrative offices — north section.',
    desc_zh: '行政北楼办公室。',
    tags_en: ['Administration'], tags_zh: ['行政'],
  },
  {
    id: 'isu-office', category: 'admin',
    name_zh: '留学生服务中心 (ISU)', name_en: 'International Students Office (ISU)',
    coords: [32.1070, 118.9062],
    desc_en: 'Office for international students. Handles visa extensions, dormitory issues, course registration, and general support.',
    desc_zh: '留学生服务中心，负责签证延期、宿舍事务、选课注册及日常支持。',
    tags_en: ['International Students', 'Visa', 'Registration', 'Support'],
    tags_zh: ['留学生', '签证', '注册', '支持'],
  },

  // ── ACADEMIC BUILDINGS ──────────────────────────────────────────────────
  {
    id: 'teaching-1', category: 'academic',
    name_zh: '教一楼（智能楼）', name_en: 'Teaching Building 1 — Smart Building',
    coords: [32.1092, 118.9058],
    desc_en: 'Smart classrooms equipped with modern AV technology.',
    desc_zh: '配备现代视听设备的智能教学楼。',
    tags_en: ['Classrooms', 'Lectures'], tags_zh: ['教室', '讲座'],
  },
  {
    id: 'teaching-2', category: 'academic',
    name_zh: '教二楼（行知楼）', name_en: 'Teaching Building 2 — Xingzhi Building',
    coords: [32.1098, 118.9058],
    desc_en: 'General lecture building for undergraduate courses.',
    desc_zh: '本科教学综合楼。',
    tags_en: ['Classrooms', 'Lectures'], tags_zh: ['教室', '讲座'],
  },
  {
    id: 'teaching-3', category: 'academic',
    name_zh: '教三楼（博理楼）', name_en: 'Teaching Building 3 — Boli Building',
    coords: [32.1104, 118.9054],
    desc_en: 'Science and engineering lecture building.',
    desc_zh: '理工科教学楼。',
    tags_en: ['Classrooms', 'Science'], tags_zh: ['教室', '理科'],
  },
  {
    id: 'teaching-4', category: 'academic',
    name_zh: '教四楼', name_en: 'Teaching Building 4',
    coords: [32.1110, 118.9050],
    desc_en: 'General lecture building.',
    desc_zh: '综合教学楼。',
    tags_en: ['Classrooms'], tags_zh: ['教室'],
  },
  {
    id: 'teaching-5', category: 'academic',
    name_zh: '教五楼', name_en: 'Teaching Building 5',
    coords: [32.1116, 118.9045],
    desc_en: 'General lecture building.',
    desc_zh: '综合教学楼。',
    tags_en: ['Classrooms'], tags_zh: ['教室'],
  },
  {
    id: 'library', category: 'academic',
    name_zh: '图书馆', name_en: 'Library',
    coords: [32.1122, 118.9072],
    desc_en: 'Main university library. Open Mon–Sun 08:00–22:00. Study spaces, digital resources, and reading rooms.',
    desc_zh: '大学图书馆，周一至周日08:00–22:00开放，提供自习室、数字资源和阅览室。',
    tags_en: ['Study', 'Books', 'Wi-Fi', 'Open Daily'],
    tags_zh: ['自习', '图书', 'Wi-Fi', '每天开放'],
  },
  {
    id: 'baimu-hall', category: 'academic',
    name_zh: '百慕馆', name_en: 'Baimu Hall',
    coords: [32.1118, 118.9060],
    desc_en: 'Multi-purpose academic hall.',
    desc_zh: '综合学术楼。',
    tags_en: ['Academic'], tags_zh: ['学术'],
  },
  {
    id: 'student-activity', category: 'academic',
    name_zh: '大学生活动中心', name_en: 'Student Activity Center',
    coords: [32.1138, 118.9082],
    desc_en: 'Hub for student clubs, societies, events, and performances.',
    desc_zh: '学生俱乐部、社团、活动和演出的中心。',
    tags_en: ['Student Life', 'Events', 'Clubs'],
    tags_zh: ['学生活动', '活动', '社团'],
  },
  {
    id: 'school-computer', category: 'academic',
    name_zh: '计算机学院楼', name_en: 'Computer Science Building',
    coords: [32.1135, 118.9020],
    desc_en: 'School of Computer Science and Technology.',
    desc_zh: '计算机学院楼。',
    tags_en: ['Computer Science', 'IT'], tags_zh: ['计算机', '信息技术'],
  },
  {
    id: 'school-telecom', category: 'academic',
    name_zh: '通信工程学院楼', name_en: 'Telecommunications Engineering Building',
    coords: [32.1148, 118.9025],
    desc_en: 'School of Telecommunications and Information Engineering.',
    desc_zh: '通信与信息工程学院楼。',
    tags_en: ['Telecommunications', 'Engineering'],
    tags_zh: ['通信', '工程'],
  },
  {
    id: 'school-electronic', category: 'academic',
    name_zh: '电子科学与工程学院楼', name_en: 'Electronic Science & Engineering Building',
    coords: [32.1142, 118.9020],
    desc_en: 'School of Electronic Science and Engineering.',
    desc_zh: '电子科学与工程学院楼。',
    tags_en: ['Electronics', 'Engineering'], tags_zh: ['电子', '工程'],
  },
  {
    id: 'school-automation', category: 'academic',
    name_zh: '自动化学院楼', name_en: 'Automation School Building',
    coords: [32.1130, 118.9018],
    desc_en: 'School of Automation.',
    desc_zh: '自动化学院楼。',
    tags_en: ['Automation', 'Engineering'], tags_zh: ['自动化', '工程'],
  },

  // ── DINING ──────────────────────────────────────────────────────────────
  {
    id: 'canteen-south', category: 'food',
    name_zh: '南食堂', name_en: 'South Canteen',
    coords: [32.1100, 118.9108],
    desc_en: 'Main dining hall in the south area. Chinese cuisine, noodles, and rice dishes. Open 07:00–20:00.',
    desc_zh: '南区主食堂，供应中式料理、面食和米饭，开放时间07:00–20:00。',
    tags_en: ['Food', 'Cafeteria', 'Open Daily'],
    tags_zh: ['餐饮', '食堂', '每天开放'],
  },
  {
    id: 'canteen-north', category: 'food',
    name_zh: '北食堂（南1/南2/南3食堂）', name_en: 'North Canteen (South 1 / 2 / 3)',
    coords: [32.1160, 118.9082],
    desc_en: 'Large dining complex with 3 canteens. Variety of Chinese, hot-pot, and grilled options. Halal section available.',
    desc_zh: '大型食堂综合体，含3个分食堂（南1/南2/南3），提供中餐、火锅、烧烤等，设有清真专区。',
    tags_en: ['Food', 'Cafeteria', 'Halal', 'Large'],
    tags_zh: ['餐饮', '食堂', '清真', '大型'],
  },

  // ── COURIER STATIONS ────────────────────────────────────────────────────
  {
    id: 'courier-jd', category: 'courier',
    name_zh: '京东快递站', name_en: 'JD Express Station',
    coords: [32.1096, 118.9092],
    desc_en: 'JD.com courier pickup and drop-off. Open 09:00–21:00.',
    desc_zh: '京东快递自提点，开放时间09:00–21:00。',
    tags_en: ['JD', 'Delivery', 'Parcel'],
    tags_zh: ['京东', '快递', '包裹'],
  },
  {
    id: 'courier-sf', category: 'courier',
    name_zh: '顺丰快递站', name_en: 'SF Express Station',
    coords: [32.1102, 118.9095],
    desc_en: 'SF Express (顺丰) station for sending and receiving parcels.',
    desc_zh: '顺丰速运快递站，提供寄件和收件服务。',
    tags_en: ['SF Express', 'Delivery', 'Parcel'],
    tags_zh: ['顺丰', '快递', '包裹'],
  },
  {
    id: 'courier-cainiao', category: 'courier',
    name_zh: '菜鸟驿站', name_en: 'Cainiao Station (Alibaba)',
    coords: [32.1117, 118.9075],
    desc_en: 'Cainiao (Alibaba logistics) parcel pickup. Accepts Taobao, Tmall, and Alibaba deliveries.',
    desc_zh: '菜鸟裹裹驿站，接受淘宝、天猫、阿里巴巴快递自提。',
    tags_en: ['Cainiao', 'Taobao', 'Alibaba', 'Delivery'],
    tags_zh: ['菜鸟', '淘宝', '阿里巴巴', '快递'],
  },
  {
    id: 'courier-ems', category: 'courier',
    name_zh: '邮政快递站（EMS）', name_en: 'China Post / EMS Station',
    coords: [32.1107, 118.9062],
    desc_en: 'China Post EMS station. Handles international and domestic parcels.',
    desc_zh: '中国邮政EMS站，处理国际和国内包裹。',
    tags_en: ['EMS', 'China Post', 'International', 'Domestic'],
    tags_zh: ['EMS', '邮政', '国际', '国内'],
  },

  // ── SERVICES ────────────────────────────────────────────────────────────
  {
    id: 'atm-east', category: 'service',
    name_zh: 'ATM机（东区）', name_en: 'ATM Machines (East Area)',
    coords: [32.1120, 118.9128],
    desc_en: 'Multiple bank ATMs. Supports UnionPay, Visa, and Mastercard.',
    desc_zh: '多家银行ATM机，支持银联、Visa、Mastercard。',
    tags_en: ['ATM', 'Bank', 'Cash', 'UnionPay'],
    tags_zh: ['ATM', '银行', '取款', '银联'],
  },
  {
    id: 'atm-center', category: 'service',
    name_zh: 'ATM机（中区）', name_en: 'ATM Machines (Central Area)',
    coords: [32.1125, 118.9072],
    desc_en: 'Bank ATM machines in the central campus area.',
    desc_zh: '校园中区银行ATM机。',
    tags_en: ['ATM', 'Bank', 'Cash'],
    tags_zh: ['ATM', '银行', '取款'],
  },
  {
    id: 'clinic', category: 'service',
    name_zh: '校医室', name_en: 'Campus Clinic',
    coords: [32.1112, 118.9082],
    desc_en: 'Campus health clinic. Consultations, prescriptions, and basic treatments. Open Mon–Fri 08:00–17:00.',
    desc_zh: '校医室，提供门诊、处方和基础治疗，周一至周五08:00–17:00开放。',
    tags_en: ['Health', 'Medical', 'Clinic'],
    tags_zh: ['医疗', '健康', '诊室'],
  },
  {
    id: 'supermarket', category: 'service',
    name_zh: '超市', name_en: 'Campus Supermarket',
    coords: [32.1128, 118.9068],
    desc_en: 'Campus supermarket. Daily necessities, snacks, drinks, and toiletries.',
    desc_zh: '校园超市，销售日用品、零食、饮料和洗漱用品。',
    tags_en: ['Supermarket', 'Groceries', 'Shopping'],
    tags_zh: ['超市', '购物', '日用品'],
  },
  {
    id: 'bookstore', category: 'service',
    name_zh: '邮苑书店', name_en: 'Youyuan Bookstore',
    coords: [32.1124, 118.9068],
    desc_en: 'Campus bookstore. Textbooks, stationery, and NJUPT souvenirs.',
    desc_zh: '邮苑书店，销售教材、文具和南邮纪念品。',
    tags_en: ['Bookstore', 'Textbooks', 'Stationery'],
    tags_zh: ['书店', '教材', '文具'],
  },
  {
    id: 'repair-shop', category: 'service',
    name_zh: '修车铺', name_en: 'Bike Repair Shop',
    coords: [32.1130, 118.9060],
    desc_en: 'Bicycle and e-bike repair, maintenance, and tyre inflation.',
    desc_zh: '自行车和电动车维修、保养及充气服务。',
    tags_en: ['Bike Repair', 'E-bike'], tags_zh: ['修车', '电动车'],
  },
  {
    id: 'mobile-topup', category: 'service',
    name_zh: '手机充值营业厅', name_en: 'Mobile Top-Up Center',
    coords: [32.1122, 118.9058],
    desc_en: 'Mobile phone top-up, SIM card purchase, and telecom services.',
    desc_zh: '手机充值、SIM卡购买和电信服务。',
    tags_en: ['Mobile', 'SIM Card', 'Top-Up'],
    tags_zh: ['充值', 'SIM卡', '手机'],
  },

  // ── SPORTS ──────────────────────────────────────────────────────────────
  {
    id: 'gymnasium', category: 'sports',
    name_zh: '新体育馆', name_en: 'New Gymnasium',
    coords: [32.1158, 118.9028],
    desc_en: 'Indoor gymnasium with basketball courts, badminton, table tennis, and a fitness centre.',
    desc_zh: '室内体育馆，设有篮球场、羽毛球、乒乓球和健身房。',
    tags_en: ['Basketball', 'Badminton', 'Gym', 'Indoor'],
    tags_zh: ['篮球', '羽毛球', '健身', '室内'],
  },
  {
    id: 'north-sports', category: 'sports',
    name_zh: '北区运动场', name_en: 'North Sports Field',
    coords: [32.1178, 118.9060],
    desc_en: '400 m outdoor running track and football field.',
    desc_zh: '400米室外跑道和足球场。',
    tags_en: ['Running', 'Football', 'Track', 'Outdoor'],
    tags_zh: ['跑步', '足球', '跑道', '室外'],
  },
  {
    id: 'north-basketball', category: 'sports',
    name_zh: '北篮球场', name_en: 'North Basketball Courts',
    coords: [32.1183, 118.9078],
    desc_en: 'Outdoor basketball courts in the north area.',
    desc_zh: '北区室外篮球场。',
    tags_en: ['Basketball', 'Outdoor'], tags_zh: ['篮球', '室外'],
  },
  {
    id: 'south-sports', category: 'sports',
    name_zh: '南区运动场', name_en: 'South Sports Field',
    coords: [32.1130, 118.9128],
    desc_en: 'Outdoor track and sports field — south area.',
    desc_zh: '南区室外运动场和跑道。',
    tags_en: ['Running', 'Sports', 'Outdoor'],
    tags_zh: ['跑步', '运动', '室外'],
  },
  {
    id: 'south-basketball', category: 'sports',
    name_zh: '南区篮球场', name_en: 'South Basketball Courts',
    coords: [32.1140, 118.9138],
    desc_en: 'Outdoor basketball courts in the south area.',
    desc_zh: '南区室外篮球场。',
    tags_en: ['Basketball', 'Outdoor'], tags_zh: ['篮球', '室外'],
  },
  {
    id: 'handball-court', category: 'sports',
    name_zh: '战旗打场（多功能球场）', name_en: 'Multi-use Court (Handball / Volleyball)',
    coords: [32.1125, 118.9115],
    desc_en: 'Multi-purpose outdoor court for handball, volleyball, and other sports.',
    desc_zh: '多功能室外运动场，可用于手球、排球等运动。',
    tags_en: ['Handball', 'Volleyball', 'Outdoor'],
    tags_zh: ['手球', '排球', '室外'],
  },

  // ── DORMITORIES ─────────────────────────────────────────────────────────
  { id: 'dorm-1',  category: 'dorm', name_zh: '1号宿舍楼',  name_en: 'Dormitory 1',
    coords: [32.1082, 118.9118], desc_en: 'Student dormitory 1.',  desc_zh: '1号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-5',  category: 'dorm', name_zh: '5号宿舍楼',  name_en: 'Dormitory 5',
    coords: [32.1090, 118.9118], desc_en: 'Student dormitory 5.',  desc_zh: '5号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-10', category: 'dorm', name_zh: '10号宿舍楼', name_en: 'Dormitory 10',
    coords: [32.1098, 118.9125], desc_en: 'Student dormitory 10.', desc_zh: '10号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-15', category: 'dorm', name_zh: '15号宿舍楼', name_en: 'Dormitory 15',
    coords: [32.1128, 118.9125], desc_en: 'Student dormitory 15.', desc_zh: '15号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-20', category: 'dorm', name_zh: '20号宿舍楼', name_en: 'Dormitory 20',
    coords: [32.1135, 118.9118], desc_en: 'Student dormitory 20.', desc_zh: '20号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-25', category: 'dorm', name_zh: '25号宿舍楼', name_en: 'Dormitory 25',
    coords: [32.1142, 118.9108], desc_en: 'Student dormitory 25.', desc_zh: '25号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-30', category: 'dorm', name_zh: '30号宿舍楼', name_en: 'Dormitory 30',
    coords: [32.1148, 118.9098], desc_en: 'Student dormitory 30.', desc_zh: '30号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-35', category: 'dorm', name_zh: '35号宿舍楼', name_en: 'Dormitory 35',
    coords: [32.1155, 118.9090], desc_en: 'Student dormitory 35.', desc_zh: '35号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-40', category: 'dorm', name_zh: '40号宿舍楼', name_en: 'Dormitory 40',
    coords: [32.1158, 118.9098], desc_en: 'Student dormitory 40.', desc_zh: '40号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-45', category: 'dorm', name_zh: '45号宿舍楼', name_en: 'Dormitory 45',
    coords: [32.1162, 118.9108], desc_en: 'Student dormitory 45.', desc_zh: '45号学生宿舍楼。',
    tags_en: ['Dormitory'], tags_zh: ['宿舍'] },
  { id: 'dorm-north', category: 'dorm', name_zh: '北区宿舍（7–19号）', name_en: 'North Dormitories (7–19)',
    coords: [32.1170, 118.9025], desc_en: 'North area dormitory cluster (buildings 7–19).',
    desc_zh: '北区宿舍群（7–19号）。',
    tags_en: ['Dormitory', 'North Area'], tags_zh: ['宿舍', '北区'] },

  // ── LANDMARKS ───────────────────────────────────────────────────────────
  {
    id: 'zhongbo-lake', category: 'landmark',
    name_zh: '中博湖', name_en: 'Zhongbo Lake',
    coords: [32.1082, 118.9090],
    desc_en: 'Scenic lake in the south area. Popular spot for relaxation and photography.',
    desc_zh: '南区风景湖，是休闲和摄影的热门地点。',
    tags_en: ['Scenic', 'Lake', 'Photography'],
    tags_zh: ['风景', '湖', '摄影'],
  },
  {
    id: 'wishing-tree', category: 'landmark',
    name_zh: '许愿树', name_en: 'Wishing Tree',
    coords: [32.1120, 118.9002],
    desc_en: 'The beloved wishing tree — a campus tradition where students hang their wishes.',
    desc_zh: '校园传统许愿树，学生在此挂上心愿。',
    tags_en: ['Landmark', 'Tradition', 'Photo Spot'],
    tags_zh: ['地标', '传统', '打卡'],
  },
  {
    id: 'ding-hill', category: 'landmark',
    name_zh: '鼎山', name_en: 'Ding Hill',
    coords: [32.1142, 118.9030],
    desc_en: 'Forested hill in the heart of campus with peaceful walking paths.',
    desc_zh: '校园中心的绿化小山，有宁静的步行小路。',
    tags_en: ['Nature', 'Hill', 'Walking'],
    tags_zh: ['自然', '小山', '散步'],
  },
  {
    id: 'golden-chestnut', category: 'landmark',
    name_zh: '金栗子山', name_en: 'Golden Chestnut Hill',
    coords: [32.1118, 118.9088],
    desc_en: 'Tree-covered hill named after the golden chestnut trees that bloom each autumn.',
    desc_zh: '以秋天盛开的金栗树命名的小山。',
    tags_en: ['Nature', 'Hill', 'Autumn'],
    tags_zh: ['自然', '小山', '秋季'],
  },
  {
    id: 'flag-square', category: 'landmark',
    name_zh: '旗广场', name_en: 'Flag Square',
    coords: [32.1126, 118.9062],
    desc_en: 'Main campus flag-raising square. National-holiday ceremonies held here.',
    desc_zh: '校园主旗广场，国家节假日在此举行升旗仪式。',
    tags_en: ['Square', 'Ceremonies', 'Landmark'],
    tags_zh: ['广场', '仪式', '地标'],
  },
  {
    id: 'wuyue-pavilion', category: 'landmark',
    name_zh: '无岳亭', name_en: 'Wuyue Pavilion',
    coords: [32.1082, 118.9050],
    desc_en: 'Traditional Chinese pavilion near the south gate area.',
    desc_zh: '南门附近的传统中国亭子。',
    tags_en: ['Pavilion', 'Traditional', 'Architecture'],
    tags_zh: ['亭子', '传统', '建筑'],
  },
];
